# Generated by Django 5.1.4 on 2025-01-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("favorite_genres", models.CharField(max_length=255)),
                ("favorite_authors", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
